/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistema.compra.e.vendas;

import javax.swing.JOptionPane;
import sistema.compra.e.vendas.dao.ClienteDAO;
import sistema.compra.e.vendas.dao.FornecedorDAO;
import sistema.compra.e.vendas.dao.NotaDAO;
import sistema.compra.e.vendas.dao.ProdutoDAO;
import sistema.compra.e.vendas.entity.Cliente;
import sistema.compra.e.vendas.entity.Fornecedor;
import sistema.compra.e.vendas.entity.Nota;
import sistema.compra.e.vendas.entity.Produto;
import sistema.compra.e.vendas.view.AtualizarCliente;
import sistema.compra.e.vendas.view.AtualizarFornecedor;
import sistema.compra.e.vendas.view.AtualizarProduto;
import sistema.compra.e.vendas.view.CadastroCliente;
import sistema.compra.e.vendas.view.CadastroFornecedor;
import sistema.compra.e.vendas.view.CadastroProduto;
import sistema.compra.e.vendas.view.LancamentoNota;
import sistema.compra.e.vendas.view.RelatorioClientes;
import sistema.compra.e.vendas.view.RelatorioFornecedores;
import sistema.compra.e.vendas.view.RelatorioNotas;
import sistema.compra.e.vendas.view.RelatorioProdutos;

/**
 *
 * @author 2830482411031
 */
public class SistemaCompraEvenda extends javax.swing.JFrame {

    /**
     * Creates new form SistemaCompraEvenda
     */
    public SistemaCompraEvenda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnProduto = new javax.swing.JButton();
        btnClientes = new javax.swing.JButton();
        btnEntrada = new javax.swing.JButton();
        btnSaida = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnListarProdutos = new javax.swing.JToggleButton();
        btnListarClientes = new javax.swing.JToggleButton();
        btnListarFornecedores = new javax.swing.JToggleButton();
        btnListarNotas = new javax.swing.JToggleButton();
        btnDeletar = new javax.swing.JToggleButton();
        btnConsultar = new javax.swing.JToggleButton();
        btnAtualizar = new javax.swing.JToggleButton();
        btnCadastroFornec = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnProduto.setText("cadastro produtos");
        btnProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProdutoActionPerformed(evt);
            }
        });

        btnClientes.setText("cadastro clientes");
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnEntrada.setText("nota entrada");
        btnEntrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaActionPerformed(evt);
            }
        });

        btnSaida.setText("nota saida");
        btnSaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaidaActionPerformed(evt);
            }
        });

        jLabel1.setText("menu estoque");

        btnListarProdutos.setText("Listar Produtos");
        btnListarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarProdutosActionPerformed(evt);
            }
        });

        btnListarClientes.setText("Listar Clientes");
        btnListarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarClientesActionPerformed(evt);
            }
        });

        btnListarFornecedores.setText("Listar Fornecedores");
        btnListarFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarFornecedoresActionPerformed(evt);
            }
        });

        btnListarNotas.setText("Listar Notas");
        btnListarNotas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnListarNotasActionPerformed(evt);
            }
        });

        btnDeletar.setText("Deletar");
        btnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        btnCadastroFornec.setText("cadastro Fornecedores");
        btnCadastroFornec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastroFornecActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnEntrada, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnProduto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSaida, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnListarProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnListarFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(btnListarNotas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCadastroFornec, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel1)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnCadastroFornec)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAtualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btnConsultar)
                        .addGap(18, 18, 18)
                        .addComponent(btnDeletar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnProduto)
                            .addComponent(btnListarProdutos))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnClientes)
                            .addComponent(btnListarClientes))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEntrada)
                            .addComponent(btnListarFornecedores))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSaida)
                            .addComponent(btnListarNotas))))
                .addContainerGap(94, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProdutoActionPerformed
        CadastroProduto cadastroProduto  = new CadastroProduto();
        cadastroProduto.setLocationRelativeTo(this);
        cadastroProduto.setVisible(true);
    }//GEN-LAST:event_btnProdutoActionPerformed

    private void btnListarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarProdutosActionPerformed
        new RelatorioProdutos().setVisible(true);
    }//GEN-LAST:event_btnListarProdutosActionPerformed

    private void btnListarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarClientesActionPerformed
        new RelatorioClientes().setVisible(true);
    }//GEN-LAST:event_btnListarClientesActionPerformed

    private void btnListarFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarFornecedoresActionPerformed
        new RelatorioFornecedores().setVisible(true);
    }//GEN-LAST:event_btnListarFornecedoresActionPerformed

    private void btnListarNotasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnListarNotasActionPerformed
        new RelatorioNotas().setVisible(true);
    }//GEN-LAST:event_btnListarNotasActionPerformed

    private void btnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletarActionPerformed
        String[] opcoes = {"Cliente", "Fornecedor", "Produto", "Nota"};
        String escolha = (String) JOptionPane.showInputDialog(
            this,
            "Escolha o tipo de cadastro que deseja excluir:",
            "Excluir",
            JOptionPane.QUESTION_MESSAGE,
            null,
            opcoes,
            opcoes[0]
        );

        if (escolha == null) return;

        String idStr = JOptionPane.showInputDialog(this, "Digite o código do " + escolha + " para excluir:");
        if (idStr == null || idStr.isEmpty()) return;

        int id = Integer.parseInt(idStr);

        int confirm = JOptionPane.showConfirmDialog(this,
            "Tem certeza que deseja excluir o " + escolha + " de código " + id + "?",
            "Confirmação",
            JOptionPane.YES_NO_OPTION);

        if (confirm != JOptionPane.YES_OPTION) return;

        switch (escolha) {
            case "Cliente":
                new ClienteDAO().excluirCliente(id);
                JOptionPane.showMessageDialog(this, "Cliente excluído com sucesso!");
                break;
            case "Fornecedor":
                new FornecedorDAO().excluirFornecedor(id);
                JOptionPane.showMessageDialog(this, "Fornecedor excluído com sucesso!");
                break;
            case "Produto":
                new ProdutoDAO().excluirProduto(id);
                JOptionPane.showMessageDialog(this, "Produto excluído com sucesso!");
                break;
            case "Nota":
                new NotaDAO().excluirNota(id);
                JOptionPane.showMessageDialog(this, "Nota excluída com sucesso!");
                break;
        }
    }//GEN-LAST:event_btnDeletarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String[] opcoes = {"Cliente", "Fornecedor", "Produto", "Nota"};
        String escolha = (String) JOptionPane.showInputDialog(
            this,
            "Escolha o tipo de cadastro para consultar:",
            "Consultar",
            JOptionPane.QUESTION_MESSAGE,
            null,
            opcoes,
            opcoes[0]
        );

        if (escolha == null) return;

        String idStr = JOptionPane.showInputDialog(this, "Digite o código do " + escolha + ":");
        if (idStr == null || idStr.isEmpty()) return;

        int id = Integer.parseInt(idStr);

        switch (escolha) {
            case "Cliente":
                ClienteDAO cdao = new ClienteDAO();
                Cliente cli = cdao.getCliente(id);
                if (cli != null)
                    JOptionPane.showMessageDialog(this, "Cliente encontrado:\n\n" +
                        "Nome: " + cli.getNome() + "\n" +
                        "Endereço: " + cli.getEndereco() + "\n" +
                        "Email: " + cli.getEmail() + "\n" +
                        "Telefone: " + cli.getTelefone());
                else
                    JOptionPane.showMessageDialog(this, "Cliente não encontrado!");
                break;

            case "Fornecedor":
                FornecedorDAO fdao = new FornecedorDAO();
                Fornecedor f = fdao.getFornecedor(id);
                if (f != null)
                    JOptionPane.showMessageDialog(this, "Fornecedor encontrado:\n\n" +
                        "Nome: " + f.getNome() + "\n" +
                        "Fantasia: " + f.getNome_fantasia() + "\n" +
                        "CNPJ: " + f.getCnpj() + "\n" +
                        "Email: " + f.getEmail() + "\n" +
                        "Telefone: " + f.getTelefone());
                else
                    JOptionPane.showMessageDialog(this, "Fornecedor não encontrado!");
                break;

            case "Produto":
                ProdutoDAO pdao = new ProdutoDAO();
                Produto p = pdao.getProduto(id);
                if (p != null)
                    JOptionPane.showMessageDialog(this, "Produto encontrado:\n\n" +
                        "Nome: " + p.getNome() + "\n" +
                        "Descrição: " + p.getDescricao() + "\n" +
                        "Preço: " + p.getPreco_venda() + "\n" +
                        "Estoque: " + p.getQtd_estoque());
                else
                    JOptionPane.showMessageDialog(this, "Produto não encontrado!");
                break;

            case "Nota":
                NotaDAO ndao = new NotaDAO();
                Nota n = ndao.getNota(id);
                if (n != null)
                    JOptionPane.showMessageDialog(this, "Nota encontrada:\n\n" +
                        "Tipo: " + n.getTipo() + "\n" +
                        "Data: " + n.getData() + "\n" +
                        "Cliente: " + n.getCod_cliente() + "\n" +
                        "Fornecedor: " + n.getCod_fornecedor());
                else
                    JOptionPane.showMessageDialog(this, "Nota não encontrada!");
                break;
        }
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        String[] opcoes = {"Cliente", "Fornecedor", "Produto"};
        int escolha = JOptionPane.showOptionDialog(
            this,
            "Qual tipo de registro você deseja atualizar?",
            "Atualizar Registro",
            JOptionPane.DEFAULT_OPTION,
            JOptionPane.QUESTION_MESSAGE,
            null,
            opcoes,
            opcoes[0]
        );

        switch (escolha) {
            case 0: 
                AtualizarCliente atualizarCliente = new AtualizarCliente();
                atualizarCliente.setLocationRelativeTo(this);
                atualizarCliente.setVisible(true);
                break;
            case 1: 
                AtualizarFornecedor atualizarFornecedor = new AtualizarFornecedor();
                atualizarFornecedor.setLocationRelativeTo(this);
                atualizarFornecedor.setVisible(true);
                break;
            case 2: 
                AtualizarProduto atualizarProduto = new AtualizarProduto();
                atualizarProduto.setLocationRelativeTo(this);
                atualizarProduto.setVisible(true);
                break;
            case JOptionPane.CLOSED_OPTION:
                
                System.out.println("Nenhuma opção de atualização selecionada.");
break;
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    private void btnCadastroFornecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastroFornecActionPerformed
        CadastroFornecedor cadastroFornecedor= new CadastroFornecedor();
        cadastroFornecedor.setLocationRelativeTo(this);
        cadastroFornecedor.setVisible(true);
    }//GEN-LAST:event_btnCadastroFornecActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
        CadastroCliente cadastroCliente = new CadastroCliente();
        cadastroCliente.setLocationRelativeTo(this);
        cadastroCliente.setVisible(true);
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnEntradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaActionPerformed
        LancamentoNota telaEntrada = new LancamentoNota("Entrada");
        telaEntrada.setVisible(true);
    }//GEN-LAST:event_btnEntradaActionPerformed

    private void btnSaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaidaActionPerformed
        LancamentoNota telaSaida = new LancamentoNota("Saida");
        telaSaida.setVisible(true);
    }//GEN-LAST:event_btnSaidaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SistemaCompraEvenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SistemaCompraEvenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SistemaCompraEvenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SistemaCompraEvenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SistemaCompraEvenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAtualizar;
    private javax.swing.JToggleButton btnCadastroFornec;
    private javax.swing.JButton btnClientes;
    private javax.swing.JToggleButton btnConsultar;
    private javax.swing.JToggleButton btnDeletar;
    private javax.swing.JButton btnEntrada;
    private javax.swing.JToggleButton btnListarClientes;
    private javax.swing.JToggleButton btnListarFornecedores;
    private javax.swing.JToggleButton btnListarNotas;
    private javax.swing.JToggleButton btnListarProdutos;
    private javax.swing.JButton btnProduto;
    private javax.swing.JButton btnSaida;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
